version: "3.2"

services:
  zoo1:
    image: zookeeper:3.5
    container_name: zoo1
    restart: always
    hostname: zoo1
    ports:
       - "2181:2181"

  kafka:
    image: trellisldp/kafka
    container_name: kafka
    ports:
      - target: 9094
        published: 9094
        protocol: tcp
        mode: host
    environment:
      HOSTNAME_COMMAND: "ifconfig|grep inet|head -1|sed 's/\\:/ /'|awk '{print $$3}'"
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_PROTOCOL_NAME: OUTSIDE
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_PROTOCOL_NAME: INSIDE
      KAFKA_PORT: 9092
    volumes:
      - kafka-data-volume:/kafka

  trellis:
    image: trellisldp/trellis-app:0.1.0
    container_name: trellis
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - trellis-data-volume:/var/lib/trellis

  trellis-processing:
    image: trellisldp/trellis-processing:0.1.0
    container_name: trellis-processing
    volumes:
      - trellis-data-volume:/var/lib/trellis

volumes:
  trellis-data-volume:
    driver_opts:
      type: none
      device: /mnt/trellis-data
      o: bind
  kafka-data-volume:
    driver_opts:
      type: none
      device: /mnt/kafka-data
      o: bind
