version: "3.2"

services:
  druid:
    image: trellisldp/imply:2.3.7
    container_name: imply
    ports:
      - "8081-8110:8081-8110"
      - "8200:8200"
      - "9095:9095"
    networks:
      - trelliscompose_default

networks:
  trelliscompose_default:
    external: true