version: "3.2"

services:
  druid:
    image: trellisldp/activitystream-dataset
    container_name: activitystream-dataset
    networks:
      - trelliscompose_default
    ports:
      - "3330:3330"

networks:
  trelliscompose_default:
    external: true